server:
  port: 8000
eureka:
  instance:
    prefer-ip-address: true #是否显示主机的IP
  client:
    service-url:
      defaultZone: http://172.19.100.130:8761/eureka/           # 指定Eureka服务端地址
spring:
  application:
    name: microservice-eureka-user # 指定应用名称